apache/yunikorn-site

- docs/api/cluster.md
- docs/api/scheduler.md
- docs/api/system.md
- sidebars.js
Work done:
- added a new dropdown menu to the site ("API Documentation") 
- added three pages: `Cluster`, `Scheduler` and `System` that list all the available endpoints from `scheduler/routes.go` grouping them by first path item
- used https://github.com/jamescooke/restapidocs for formatting, but I'm open to any suggestions if you have some problems
The examples are extracted via a locally running running a YK scheduler instance, and crawling the 9080 port on my laptop.
> [YUNIKORN-306] Add yunikorn rest api document

- docs/design/scheduler_core_design.md
The current grammar will cause the title rendering to fail, the case is here: http://yunikorn.apache.org/docs/next/design/scheduler_core_design/
> [YUNIKORN-424] Fix nonstandard title grammar for the markdown file

- docs/user_guide/workloads/run_spark.md
We need to specify the namespace for the subjects since the -n doesn't propegate the NS to subject. Might as well put the SA inside of the NS while were at it.
> [YUNIKORN-727] Fix Spark RBAC in workspace examples

- docs/api/scheduler.md
Doc changes to clearly explain the Old and Newer version API's use.
> YUNIKORN-746: Simplify the REST API document

- src/pages/community/download.md
The command mentioned on the download page have non ascii chars embedded.
It also provides the wrong command for the checksum validation.
> [YUNIKORN-779] fix commands on download page

- Dockerfile
- README.md
- local-build.sh
- package.json
The search theme requires a later version of node.js to build.
Fix the local build script and the README to add the search dependency.
Update node to the current release 16.13.
Upgrade docusaurus to the latest v2 beta release (moving away from the
current alpha release)
> [YUNIKORN-944] Fix build dependencies

- src/pages/community/get_involved.md
Replace the expired links. Also, use a more sharable google calendar link.
> [YUNIKORN-1037] Update community conf links.

- docusaurus.config.js
- src/pages/community/get_involved.md
- src/pages/community/people.md
This adds a page at community/people, and a list of PPMC/committer names.
And move "become a committer/PPMC" to this page because it is more relevant.
Sorry forgot to take a screenshot, but I've tested this locally, it works fine. Please help to review the content. Thanks!
> [YUNIKORN-1021] Add committer/PPMC user list on the website.

- i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide
- i18n/zh-cn/docusaurus-plugin-content-docs/current/get_started/get_started.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/performance/metrics.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/performance/performance_tutorial.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/gang_scheduling.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/trouble_shooting.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/workloads/run_spark.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/workloads/run_tensorflow.md
- i18n/zh-cn/docusaurus-plugin-content-docs/version-0.12.1/developer_guide
- i18n/zh-cn/docusaurus-plugin-content-docs/version-0.12.1/get_started/get_started.md
- i18n/zh-cn/docusaurus-plugin-content-docs/version-0.12.1/performance/metrics.md
- i18n/zh-cn/docusaurus-plugin-content-docs/version-0.12.1/performance/performance_tutorial.md
- i18n/zh-cn/docusaurus-plugin-content-docs/version-0.12.1/user_guide/gang_scheduling.md
- i18n/zh-cn/docusaurus-plugin-content-docs/version-0.12.1/user_guide/trouble_shooting.md
- i18n/zh-cn/docusaurus-plugin-content-docs/version-0.12.1/user_guide/workloads/run_spark.md
- i18n/zh-cn/docusaurus-plugin-content-docs/version-0.12.1/user_guide/workloads/run_tensorflow.md
Due to my negligence, I didn't verify the result by using `yarn build`.
`docusaurus` will verify the validity of the associated links in the documents at the last stage of `build`. Due to the modification of some title names, the links in some other documents fail, resulting in the failure of build:
```
[WARNING] Docs markdown link couldn't be resolved: (../../get_started/get_started.md) in /incubator-yunikorn-site/docs/user_guide/workloads/run_tensorflow.md for version current
[WARNING] Docs markdown link couldn't be resolved: (../../get_started/get_started.md) in /incubator-yunikorn-site/docs/user_guide/workloads/run_tensorflow.md for version current
[WARNING] Docs markdown link couldn't be resolved: (../../get_started/get_started.md) in …
```
> [FIX] [YUNIKORN-1059] Fix get started doc yarn build error

- i18n/zh-cn/docusaurus-plugin-content-docs/current/get_started/get_started.md
The relevant PR content in YUNIKORN-1056 issue includes the content of `get_started.md` that has been translated. Here, add an additional PR to translate the corresponding content.
> [YUNIKORN-1056] [Chinese] Supplement the scheduler plugin translation in get_started.md

- docusaurus.config.js
#Description
Update credentials which are new apiKey and appId of algolia docsearch, according to [Docsearch migration in docusaurus blog](https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration).
#Build and run(test)
> [YUNIKORN-990] DocSearch Migration

- docs/design/interface_message_simplification.md
- docs/design/scheduler_core_design.md
update scheduler core design documentation with new interface
> [YUNIKORN-864] update design documentation with new interface

- docusaurus.config.js
- package.json
Docusaurus hides the version number in the URL for the latest versions, e.g right now our latest version is 1.0.0, but http://localhost:3000/docs/1.0.0 gives a 404. Ideally, we should make have an accessible URL for this version as well. This is in order to fix: https://github.com/apache/spark/pull/37622
> [YUNIKORN-1293] Add custom redirects to the current version doc

- src/pages/community/get_involved.md
The zoom links on the community page are old expired links. Updated the new zoom links with the [google doc](https://docs.google.com/document/d/165gzC7uhcKc5XDWiMYSRKBiPQBy2tDtXADUPuhGlUa0/edit#)
The community page is not in sync with the google doc for the community sync.
> [YUNIKORN-1379] update meeting links on the community page

- i18n/zh-cn/docusaurus-plugin-content-pages/community/how_to_contribute.md
- src/pages/community/how_to_contribute.md
Update the how to contribute page with the signup procedure for jira following the auto signup disablement by Apache Infra.
Special focus on the zn-ch translation.
> [YUNIKORN-1444] jira signup procedure

- docusaurus.config.js
- i18n/zh-cn/docusaurus-plugin-content-pages/release-announce/0.12.2.md
- src/pages/release-announce/0.12.2.md
- src/pages/release-announce/1.1.0.md
Point to web accessible links in announcements
Remove unneeded base regexp in config
Note: zh-cn release announcement for 1.1.0 is missing
https://issues.apache.org/jira/browse/YUNIKORN-1521
Links in the release announcements should open correct page
Followed link in the v1.1.0 release announcement for fixed jiras:
> [YUNIKORN-1521] fix broken release announcement links

- src/pages/community/events.md
Add the recent KubeConf talk to Events page
N/A
https://issues.apache.org/jira/browse/YUNIKORN-1539
> [YUNIKORN-1539] Add KubeConf talk info to events page

- docs/performance/metrics.md
https://yunikorn.apache.org/docs/next/performance/metrics has never been updated after https://github.com/apache/yunikorn-site/commit/be96059df4c40a926e59696f997a70ba9fea6d40. Part of the metrics documentation not aligns with the yunikorn-core master branch. e.g. tryPreemptionLatency not mentioned in doc
https://issues.apache.org/jira/browse/YUNIKORN-1970
> [YUNIKORN-1970] Fix outdated metrics document

- docs/archived_design/k8shim.md
- versioned_docs/version-0.10.0/design/k8shim.md
- versioned_docs/version-0.11.0/design/k8shim.md
- versioned_docs/version-0.12.1/design/k8shim.md
- versioned_docs/version-0.12.2/design/k8shim.md
- versioned_docs/version-0.9.0/design/k8shim.md
- versioned_docs/version-1.0.0/design/k8shim.md
- versioned_docs/version-1.1.0/design/k8shim.md
- versioned_docs/version-1.2.0/archived_design/k8shim.md
- versioned_docs/version-1.2.0/design/k8shim.md
- versioned_docs/version-1.3.0/archived_design/k8shim.md
in https://yunikorn.apache.org/docs/next/archived_design/k8shim#the-admission-controller
the link in [mutation webhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#validatingadmissionwebhook) is
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#validatingadmissionwebhook
while it should be
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook
N/A
https://issues.apache.org/jira/browse/YUNIKORN-2011
N/A
N/A
N/A
> [YUNIKORN-2011] Incorrect link in Kubernetes Shim Design

- docs/metrics/queue.md
- Update the queue metrics documentation to describe the new queue metrics with labels to be introduced in `1.5.0`
- Add deprecation (`1.6.0`) and removal (`1.7.0`) notices for the subsystem metrics that are being replaced
https://issues.apache.org/jira/browse/YUNIKORN-970
Local build with `./local-build.sh run`
> [YUNIKORN-970] Add queue metrics with queue names as labels

- docs/user_guide/service_config.md
in  https://yunikorn.apache.org/docs/next/user_guide/service_config/#admissioncontrollerfilteringdefaultqueue
admissionController.filtering.defaultQueue default value should be `root.default` instead of empty. (see https://github.com/apache/yunikorn-k8shim/blob/28995cd7289256be3d3b8f820d438ddec36778b3/pkg/admission/conf/am_conf.go#L76)
N/A
https://issues.apache.org/jira/browse/YUNIKORN-2228
N/A
N/A
N/A
> [YUNIKORN-2228] Fix doc admissionController.filtering.defaultQueue default should be root.default

- docs/user_guide/queue_config.md
- i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/queue_config.md
Remove deprecated documentation. related to https://github.com/apache/yunikorn-core/pull/737
N/A
https://issues.apache.org/jira/browse/YUNIKORN-809
N/A
N/A
N/A
> [YUNIKORN-809] Remove old behavior that dynamical queue can extend application.sort.policy from parent

- src/pages/community/how_to_contribute.md
We should encourage user to run e2e by `run-e2e-test.sh` instead of `make e2e_test` as make e2e_test won't setup k8s testing environment.
N/A
https://issues.apache.org/jira/browse/YUNIKORN-2288
N/A
N/A
N/A
> [YUNIKORN-2288] Encourage user to run e2e by run-e2e-tests.sh instead of make e2e_test in doc

- docs/get_started/get_started.md
- docs/user_guide/observability/loki.md
- docs/user_guide/observability/prometheus.md
- sidebars.js
This pr put observability related doc in a category
Help user can quickly find out observability doc of YUNIKORN
https://issues.apache.org/jira/browse/YUNIKORN-2749
> [YUNIKORN-2749] Place all observability related doc in same directory

- docs/user_guide/workloads/run_spark.md
once [spark-operator#2209](https://issues.apache.org/jira/browse/YUNIKORN-2919?filter=-4&jql=status%20in%20(Open%2C%20Reopened)%20AND%20assignee%20in%20(currentUser())%20order%20by%20created%20DESC#2209)(https://github.com/kubeflow/spark-operator/pull/2209) merged and released, it would be `memory + memoryOverhead + spark.executor.pyspark.memory + spark.memory.offHeap.size`
https://issues.apache.org/jira/browse/YUNIKORN-2919
> [YUNIKORN-2919] Document spark-operator: Account spark.memory.offHeap.size
