community/roadmap.md
I only found this single link (all the other worked for me, trust me, I clicked on every link!).
=> [YUNIKORN-307] Review and fix all dead links in the doc

docs/api/scheduler.md
..using queue name/namespace for v1/apps endpoint
=> [YUNIKORN-283] Support query params to filter the apps..

sidebars.js
Created the PR with the reorganized sidebar. If you wish to resolve versioning the sidebar in this issue, I can do that too.
=> [YUNIKORN-338] Change order in the sidebar

community/get_invovled.md
Some improvements in the get_involved page to organize and add more content
=> YUNIKORN-381. doc changes for get_involved

src/css/custom.css
Disable docusaurus version alert for older versions. This is a quick
remove for all versions. Further customisation is possible as per
docusaurus issue #3013.
=> [YUNIKORN-353] Disable version alerts

src/pages/community/download.md
Minor fixes to download instructions not related to a specific version.
=> [YUNIKORN-616] fix download page

docs/api/cluster.md, docs/api/scheduler.md
Doc changes for all redesigned API's and describing json error responses for other API's as well.
=> YUNIKORN-515: Documentation changes for all Redesigned API's

Dockerfile, docusaurus.config.js, src/css/custom.css
What is this PR for?
Add search box in website.
Wait for API key and index name from Docsearch.
What type of PR is it?
What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-701 
How should this be tested?
I use "local-build.sh run" to check that search box exist.
For now, wait related information and API key from Docsearch.
=> [Yunikorn 701] Add search box to the website

docusaurus.config.js
What is this PR for?
Change API key and index name to fix no result problem
What type of PR is it?
What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-750
How should this be tested?
I use "local-build.sh run" to check that search box exist and result return.
Screenshot
=> [YUNIKORN-750] Website search box returns no result

docs/api/scheduler.md
What is this PR for?
Add doc for heakthcheck endpoint in REST API part.
What type of PR is it?
-[ ] Bug Fix
-[ ] Sub-task
-[x] Improvement
-[ ] Feature
-[ ] Documentation
-[ ] Hot Fix
-[ ] Refactoring
-[ ] New Feature
What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-745
How should this be tested?
Use docker or yarn to check website context.
Screenshot
=> [YUNIKORN-745] Add doc for healthcheck endpoint

LICENSE
What is this PR for?
Add apache 2.0 license file to the site repo
What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-712
=> [YUNIKORN-712] Add license file to the site repo

docs/api/scheduler.md
issue: https://issues.apache.org/jira/browse/YUNIKORN-794
tasks:
- https://github.com/apache/incubator-yunikorn-core/pull/317
- https://github.com/apache/incubator-yunikorn-web/pull/64
=> [YUNIKORN-794]  Fix a few typos in the REST API about queue capacity

docs/api/scheduler.md
issue: https://issues.apache.org/jira/browse/YUNIKORN-860
=> [YUNIKORN-860] update the docs in web site about "nodeSortingPolicy"

src/pages/community/sessions.md
=> [YUNIKORN-917] Publish the event details on the website

docusaurus.config.js, src/pages/community/events.md
=> [YUNIKORN-929] Rename sessions to events.

docusaurus.config.js
Update website to conform with the Apache requirements.
=> [YUNIKORN-856] Website errata

docs/performance/metrics.md
Add the some tables to explain each metrics in YuniKorn.
=> [YUNIKORN-925]Add document to explain existing yunikorn metrics

sidebars.js
=> [YUNIKORN-851] Documents of build kubemark and prometheus (addendum)

src/pages/community/roadmap.md, src/pages/release-announce/0.12.1.md
Release announcement update to point to URL without authentication
requirement.
=> [YUNIKORN-996] update roadmap for v1.0

src/pages/community/get_involved.md, src/pages/community/how_to_contribute.md
This PR addresses the QU 30, 40, 50 in the ASF project maturity model doc.
QU30
The project provides a well-documented, secure and private channel to report security issues, along with a documented way of responding to them.
QU40
The project puts a high priority on backwards compatibility and aims to document any incompatible changes and provide tools and documentation to help users transition to new features.
CO50
The project documents how contributors can earn more rights such as commit access or decision power, and applies these principles consistently.
=> [YUNIKORN-1006] Address QU 30, 40, 50

src/pages/community/how_to_contribute.md
Update the guidelines about reporting security issues based on community discussion
=> [YUNIKORN-1020] Update security issue report guidelines.

src/pages/community/people.md
Fix the wrong timezone for Craig.
=> [YUNIKORN-1005] Minor fix on the people page.

.github/workflows/auto-publish.yml
Fixes https://issues.apache.org/jira/browse/YUNIKORN-1055
=> [YUNIKORN-1055] Increase build timeout for auto-publish action to 10 minutes

docs/developer_guide/build.md, docs/developer_guide/deployment.md, docs/get_started/get_started.md, docs/user_guide/deployment_modes.md, package.json, sidebars.js
https://issues.apache.org/jira/browse/YUNIKORN-1056
=> [YUNIKORN-1056] Document usage of scheduler plugin

src/pages/community/events.md
Update the "Events" section of the website: https://yunikorn.apache.org/community/events
=> [YUNIKORN-1071] Update website for YuniKorn Meetup in Feb 2022

docusaurus.config.js, i18n/zh-cn/docusaurus-theme-classic/footer.json
Special request: check the Chinese changes
=> [YUNIKORN-1046] update website footer

i18n/zh-cn/docusaurus-plugin-content-pages/release-announce/0.12.2.md
Add Release Announcement v0.12.2 translation zh-cn
=> [YUNIKORN-1096] Add Release Announcement v0.12.2 translation zh-cn

i18n/zh-cn/docusaurus-plugin-content-pages/community/events.md
translate [YUNIKORN-1071](https://github.com/apache/incubator-yunikorn-site/pull/128)
=> [YUNIKORN-1071] [Chinese] translate update website for YuniKorn Meetup in Feb 2022

docs/performance/performance_tutorial.md, i18n/zh-cn/docusaurus-plugin-content-docs/current/performance/performance_tutorial.md, i18n/zh-cn/docusaurus-plugin-content-docs/version-0.12.1/performance/performance_tutorial.md, i18n/zh-cn/docusaurus-plugin-content-docs/version-0.12.2/performance/performance_tutorial.md, versioned_docs/version-0.12.1/performance/performance_tutorial.md, versioned_docs/version-0.12.2/performance/performance_tutorial.md
JIRA: https://issues.apache.org/jira/browse/YUNIKORN-1151
=> [YUNIKORN-1151] Fix the yaml comment syntax in Performance/Benchmarking Tutorial

docs/api/scheduler.md
JIRA: https://issues.apache.org/jira/browse/YUNIKORN-1174
=> [YUNIKORN-1174] Document changes from YUNIKORN-998

i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/workloads/run_flink.md, i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/workloads/run_spark.md, i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/workloads/run_tensorflow.md
JIAR https://issues.apache.org/jira/browse/YUNIKORN-1177
Translate flow documents:
=> [YUNIKORN-1177] Add Chinese translation for user guide workloads documents

i18n/zh-cn/docusaurus-plugin-content-pages/community/release_procedure.md, i18n/zh-cn/docusaurus-theme-classic/navbar.json
There are two task to do in this PR
=> [YUNIKORN-1154] Translate YuniKorn Release Procedure to zh-cn

i18n/zh-cn/docusaurus-plugin-content-pages/community/download.md, i18n/zh-cn/docusaurus-plugin-content-pages/community/roadmap.md, i18n/zh-cn/docusaurus-plugin-content-pages/release-announce/1.0.0.md
jira https://issues.apache.org/jira/browse/YUNIKORN-1223
1. Download
2. Roadmap
3. 1.0.0 Release Announcement
=> [YUNIKORN-1223] Add Chinese translation for 1.0.0 Release

docs/api/scheduler.md
JIRA: https://issues.apache.org/jira/browse/YUNIKORN-1267
=> [YUNIKORN-1267] Document requests attribute of application REST response

docs/user_guide/gang_scheduling.md, i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/gang_scheduling.md
[YUNIKORN-868](https://issues.apache.org/jira/browse/YUNIKORN-868)
=> [YUNIKORN-868] Add doc to address that placeholder now supports affinity

docs/api/scheduler.md
JIRA: https://issues.apache.org/jira/browse/YUNIKORN-1285
=> [YUNIKORN-1285] Document application-specific REST API

docs/user_guide/workloads/run_spark.md, i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/workloads/run_spark.md, i18n/zh-cn/docusaurus-plugin-content-docs/version-1.1.0/assets, package.json
fix includes correct assets link for i18n pages from 1.1.0 release
=> [YUNIKORN-1345] Updating the Spark tutorial i18n

i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/workloads/workload_overview.md
I translates workload/Overview with Chineses and links in this page are work.
https://issues.apache.org/jira/browse/YUNIKORN-1408
1.  ./local_build.sh run
2.  ./local_build.sh run zh-cn
=> [YUNIKORN-1408] Adding Chinese translation of workload/Overview

i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/workloads/run_tensorflow.md
While [YUNIKORN-1339](https://issues.apache.org/jira/browse/YUNIKORN-1339) add tutorial about time-slicing. The translate hasn't been update.
I translate "workloads/run_tf" with Chineses.
[https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-1422](https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-1422)
`./local-build.sh zh-cn`
=> [YUNIKORN-1422] Adding Chinese translations of Run TensorFlow Jobs

docs/user_guide/workloads/run_mpi.md, docs/user_guide/workloads/workload_overview.md, sidebars.js
This is a WIP due to https://github.com/apache/yunikorn-k8shim/pull/478.
=> YUNIKORN-1390 - MPIOperator Example to Yunikorn Site

i18n/zh-cn/docusaurus-plugin-content-docs/current/performance/performance_tutorial.md, i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/gang_scheduling.md, i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/troubleshooting.md, package.json
=> [YUNIKORN-1481] Broken links in zh-cn

.github/PULL_REQUEST_TEMPLATE, package.json
Add PULL_REQUEST_TEMPLATE file into .github
=> [YUNIKORN-1482] Add a PR template to keep format same

i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/usergroup_resolution.md
I translate the page `User and Group Resolution` to Chinese
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN-1409/
=> [YUNIKORN-1409] Adding Chinese translation of User and Group Resolution

i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/workloads/run_mpi.md
I translate the page `Run MPI jobs` to Chinese
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN-1504/
=> [YUNIKORN-1504] Chinese translation of Run MPI jobs in workload

i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/troubleshooting.md
I translate the page `troubleshooting` to Chinese
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN-1503/
=> [YUNIKORN-1503] Chinese translation of troubleshooting

src/pages/community/release_procedure.md
The procedure around the signing of the helm charts lacks details on how to get the correct gpg key and where it is stored.
https://issues.apache.org/jira/browse/YUNIKORN-1313
Next release will use the steps
=> [YUNIKORN-1313] update release procedure for helm signing

i18n/zh-cn/docusaurus-plugin-content-docs/current/api/cluster.md
I translate the page `Cluster` to Chinese
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN-1514/
=> [YUNIKORN-1514] Adding Chinese translation of Cluster

i18n/zh-cn/docusaurus-plugin-content-pages/community/people.md, src/pages/community/people.md
add new PMC and committers to the list
https://issues.apache.org/jira/browse/YUNIKORN-1554
=> [YUNIKORN-1554] Update project member list

i18n/zh-cn/docusaurus-plugin-content-docs/current/api/system.md
I translate the page `System` to Chinese
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN-1516/
=> [YUNIKORN-1516] Adding Chinese translation of System Rest API

i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/translation.md
Adding Chinese translation of developer/translation. 
https://issues.apache.org/jira/browse/YUNIKORN-1512
```
./local-build.sh run
./local-build.sh run zh-cn
```
=> [YUNIKORN-1512] Adding Chinese translation of Translation

docs/user_guide/troubleshooting.md, versioned_docs/version-1.2.0/user_guide/troubleshooting.md
Update text in Set Logging level for troubleshooting guide
https://issues.apache.org/jira/browse/YUNIKORN-1602
=> [YUNIKORN-1602] Update text in Set Logging level for troubleshooting guide

i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/service_config.md
Part of [YUNIKORN-1032](https://issues.apache.org/jira/browse/YUNIKORN-1032) Add Chinese translation for user guide documents
* [  ] - Bug Fix
* [  ] - Improvement
* [  ] - Feature
* [√] - Documentation
* [  ] - Hot Fix
* [  ] - Refactoring
=> [YUNIKORN-1507] Adding Chinese translation of Service Configuration

docs/api/scheduler.md, i18n/zh-cn/docusaurus-plugin-content-docs/current/api/scheduler.md
Update new entry into the REST interface document on English and Chinese version.
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN-1611/
=> [YUNIKORN-1611] Update the new entry into the REST interface document

docs/design/config_v2.md, docs/user_guide/service_config.md, i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/service_config.md
Update the documentation of the Instance type in the website.
Works in [YUNIKORN-1565](https://issues.apache.org/jira/browse/YUNIKORN-1565) allow yunikorn to store a node labels with map format.
https://issues.apache.org/jira/browse/YUNIKORN-1678
=> [YUNIKORN-1678] Add instance type support to doc.

versioned_sidebars/version-1.2.0-sidebars.json
Remove duplicate pages:
* K8s Scheduler Plugin
* Gang scheduling design
* Kubernetes Shim Design
https://issues.apache.org/jira/browse/YUNIKORN-1726
=> [YUNIKORN-1726] remove duplicate pages

docs/api/scheduler.md
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - http://yunikorn.apache.org/community/how_to_contribute   
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN/
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`
=> [YUNIKORN-1383] [website] REST API doc changes in Yunikorn Website

i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/env_setup.md
Adding Chinese translation for Dev environment setup
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN-1508/
=> [YUNIKORN-1508] Adding Chinese translation of Dev environment setup

i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/resource_quota_mgmt.md
Adding Chinese translation of resource quota management
=> [YUNIKORN-1416] Adding Chinese translation of resource quota management

i18n/zh-cn/docusaurus-plugin-content-pages/community/roadmap.md
Update the roadmap in the cn side.
https://issues.apache.org/jira/browse/YUNIKORN-1776
=> [YUNIKORN-1776] Update roadmap for 1.4

i18n/zh-cn/docusaurus-plugin-content-docs/current/developer_guide/openshift_development.md
Adding Chinese translation of Development in CodeReady Containers
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN-1513/
=> [YUNIKORN-1513] Adding Chinese translation of Development in CodeReady Containers

i18n/zh-cn/docusaurus-plugin-content-pages/community/people.md, src/pages/community/people.md
updated with Qi Zhu as a committer and Yu Teng Chen changed from committer to a PMC member.
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN-1911/
=> [YUNIKORN-1911] update community member list with latest changes

docs/api/scheduler.md
update REST API /ws/v1/fullstatedump document.
N/A
https://issues.apache.org/jira/browse/YUNIKORN-2018
N/A
N/A
N/A
=> [YUNIKORN-2018] Update full state dump REST API doc

docs/api/scheduler.md
Update `/ws/v1/config` response.
https://issues.apache.org/jira/browse/YUNIKORN-2014
=> [YUNIKORN-2014] update /ws/v1/config response

docs/api/cluster.md, i18n/zh-cn/docusaurus-plugin-content-docs/current/api/cluster.md
The REST API is adjust by [YUNIKORN-959](https://github.com/apache/yunikorn-core/pull/497). We need to update the document also.
[YUNIKORN-2032](https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-2032)
=> [YUNIKORN-2032] Update cluster api document

i18n/zh-cn/docusaurus-plugin-content-docs/current/design/scheduler_plugin.md
Adding Chinese translation of K8s Scheduler Plugin
https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-2002
=> [YUNIKORN-2002] Adding Chinese translation of K8s Scheduler Plugin

src/pages/community/people.md
Minor updates on the who-we-are web page, updating the profile for Junping.
https://issues.apache.org/jira/browse/YUNIKORN-2255
=> [YUNIKORN-2255] Minor updates on who-we-are page

docs/user_guide/preemption.md
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - http://yunikorn.apache.org/community/how_to_contribute   
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN/
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`
=> [YUNIKORN-2248] Fix typo "Preeemption"

docs/user_guide/resource_quota_mgmt.md, i18n/zh-cn/docusaurus-plugin-content-docs/current/user_guide/resource_quota_mgmt.md
- Fix broken hyperlinks mentioned in Jira.
- Fix another broken link in the same page.
https://github.com/apache/yunikorn-site/blob/master/docs/user_guide/resource_quota_mgmt.md?plain=1#L219
- Fix the corresponding link in Chinese document
NA
https://issues.apache.org/jira/browse/YUNIKORN-2276
> yarn start --locale=zh-cn
yarn start 
NA
NA
=> [YUNIKORN-2276] fix hyperlinks of "Resource Quota Management" page

docs/design/generic_resource.md
As title. Change the JSON representation like other documents.
https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-2278
=> [YUNIKORN-2278] fix the example of "yunikorn.apache.org/namespace.quota"

src/pages/community/people.md
Update the website to add new committer Junyan Ling
https://issues.apache.org/jira/browse/YUNIKORN-3094
=> [YUNIKORN-3094] Update the website to add new committer Junyan Ling
